<?php
class ReportService {
    public function __construct(private PDO $pdo) {}
    public function summary(string $agency): array { $s=$this->pdo->prepare("SELECT COUNT(*) total, SUM(CASE WHEN LOWER(repo_status)='open list' THEN 1 ELSE 0 END) openlist, SUM(CASE WHEN LOWER(repo_status)='contacted' THEN 1 ELSE 0 END) contacted, SUM(CASE WHEN LOWER(repo_status)='repo mark' THEN 1 ELSE 0 END) repoMark, SUM(CASE WHEN LOWER(repo_status)='parked' THEN 1 ELSE 0 END) parked, SUM(CASE WHEN LOWER(repo_status)='released' THEN 1 ELSE 0 END) released FROM vehicle WHERE agency_id=?");$s->execute([$agency]);$r=$s->fetch();return ['totalVehicles'=>(int)$r['total'],'openlist'=>(int)$r['openlist'],'contacted'=>(int)$r['contacted'],'repoMark'=>(int)$r['repoMark'],'parked'=>(int)$r['parked'],'released'=>(int)$r['released']]; }
    public function finance(string $agency,?string $finance,?string $branch): array {$sql="SELECT finance,branch,COUNT(*) totalVehicles,SUM(CASE WHEN LOWER(repo_status)='repo mark' THEN 1 ELSE 0 END) repoMarkedCount,SUM(CASE WHEN LOWER(repo_status)='parked' THEN 1 ELSE 0 END) parkedCount,SUM(CASE WHEN LOWER(repo_status)='released' THEN 1 ELSE 0 END) releasedCount FROM vehicle WHERE agency_id=?";$p=[$agency];if($finance!==null&&$finance!==''){ $sql.=' AND finance=?';$p[]=$finance;}if($branch!==null&&$branch!==''){ $sql.=' AND branch=?';$p[]=$branch;}$sql.=' GROUP BY finance,branch ORDER BY finance,branch';$s=$this->pdo->prepare($sql);$s->execute($p);return array_map(fn($r)=>['finance'=>$r['finance'],'branch'=>$r['branch'],'totalVehicles'=>(int)$r['totalVehicles'],'repoMarkedCount'=>(int)$r['repoMarkedCount'],'parkedCount'=>(int)$r['parkedCount'],'releasedCount'=>(int)$r['releasedCount']],$s->fetchAll());}
    public function monthly(string $agency,string $year,string $month): array {$s=$this->pdo->prepare("SELECT repo_year,repo_month,COUNT(*) totalVehicles,SUM(CASE WHEN UPPER(repo_status)='REPO MARK' THEN 1 ELSE 0 END) repoMarkedCount,SUM(CASE WHEN UPPER(repo_status)='PARKED' THEN 1 ELSE 0 END) parkedCount,SUM(CASE WHEN UPPER(repo_status)='RELEASED' THEN 1 ELSE 0 END) releasedCount FROM vehicle WHERE agency_id=? AND repo_year=? AND repo_month=? GROUP BY repo_year,repo_month ORDER BY repo_year DESC,repo_month DESC");$s->execute([$agency,$year,$month]);return array_map(fn($r)=>['repoYear'=>$r['repo_year'],'repoMonth'=>$r['repo_month'],'totalVehicles'=>(int)$r['totalVehicles'],'repoMarkedCount'=>(int)$r['repoMarkedCount'],'parkedCount'=>(int)$r['parkedCount'],'releasedCount'=>(int)$r['releasedCount']],$s->fetchAll());}
    public function userActivity(string $agency): array {$sql="SELECT sh.user_name,sh.user_email,sh.agency_id,COUNT(*) total_searches,SUM(CASE WHEN UPPER(v.repo_status)='REPO MARK' THEN 1 ELSE 0 END) repoMark,SUM(CASE WHEN UPPER(v.repo_status)='PARKED' THEN 1 ELSE 0 END) parked,SUM(CASE WHEN UPPER(v.repo_status)='RELEASED' THEN 1 ELSE 0 END) released,MAX(sh.search_time) lastSearchTime FROM search_history sh LEFT JOIN vehicle v ON UPPER(REPLACE(REPLACE(sh.vehicle_number,'-',''),' ',''))=UPPER(REPLACE(REPLACE(v.vehicle_number,'-',''),' ','')) WHERE sh.agency_id=? GROUP BY sh.user_name,sh.user_email,sh.agency_id ORDER BY COUNT(*) DESC";$s=$this->pdo->prepare($sql);$s->execute([$agency]);return array_map(fn($r)=>['userName'=>$r['user_name'],'userEmail'=>$r['user_email'],'agencyId'=>$r['agency_id'],'totalSearches'=>(int)$r['total_searches'],'repoMarkedCount'=>(int)$r['repoMark'],'parkedCount'=>(int)$r['parked'],'releasedCount'=>(int)$r['released'],'lastSearchTime'=>$r['lastSearchTime']],$s->fetchAll());}
    public function financeList(string $agency): array {$s=$this->pdo->prepare('SELECT DISTINCT finance FROM vehicle WHERE agency_id=? ORDER BY finance');$s->execute([$agency]);return array_values(array_filter(array_column($s->fetchAll(),'finance'),fn($x)=>$x!==null&&$x!==''));}
    public function branchList(string $agency,string $finance): array {$s=$this->pdo->prepare('SELECT DISTINCT branch FROM vehicle WHERE agency_id=? AND finance=? ORDER BY branch');$s->execute([$agency,$finance]);return array_values(array_filter(array_column($s->fetchAll(),'branch'),fn($x)=>$x!==null&&$x!==''));}
    public function vehicles(string $agency,?string $finance,?string $branch,?string $year,?string $month,string $status): array {$sql='SELECT vehicle_number,owner_name,loan_number,repo_status FROM vehicle WHERE agency_id=?';$p=[$agency];foreach([['finance',$finance],['branch',$branch],['repo_year',$year],['repo_month',$month]] as [$c,$v]){if($v!==null&&$v!==''){$sql.=" AND $c=?";$p[]=$v;}}if(strtoupper($status)!=='ALL'){$sql.=' AND UPPER(repo_status)=UPPER(?)';$p[]=$status;}$s=$this->pdo->prepare($sql);$s->execute($p);return array_map(fn($r)=>['vehicleNumber'=>$r['vehicle_number'],'ownerName'=>$r['owner_name'],'loanNumber'=>$r['loan_number'],'repoStatus'=>$r['repo_status']],$s->fetchAll());}
    public function userReport(string $email): array {$s=$this->pdo->prepare('SELECT DISTINCT vehicle_number FROM search_history WHERE user_email=?');$s->execute([$email]);$nums=array_column($s->fetchAll(),'vehicle_number');$out=['totalVehicles'=>count($nums),'repoMarked'=>0,'parked'=>0,'released'=>0];foreach($nums as $n){$norm=strtoupper(str_replace(['-',' '],'',$n));$q=$this->pdo->prepare("SELECT repo_status FROM vehicle WHERE UPPER(REPLACE(REPLACE(vehicle_number,'-',''),' ',''))=? LIMIT 1");$q->execute([$norm]);$st=$q->fetchColumn();$st=strtoupper(trim((string)$st));if($st==='REPO MARK')$out['repoMarked']++;elseif($st==='PARKED')$out['parked']++;elseif($st==='RELEASED')$out['released']++;}return $out;}
    public function yardVehicles(int $yardId,string $agency,string $status): array {$sql='SELECT v.*,y.yard_name,y.yard_address,y.yard_manager_name,y.yard_contact_no,y.agency_id yard_agency_id FROM vehicle v LEFT JOIN yard y ON y.id=v.yard_id WHERE v.yard_id=? AND v.agency_id=?';$p=[$yardId,$agency];if(strtoupper($status)!=='ALL'){$sql.=' AND UPPER(v.repo_status)=UPPER(?)';$p[]=$status;}$s=$this->pdo->prepare($sql);$s->execute($p);return $s->fetchAll();}
}
