CREATE DATABASE IF NOT EXISTS repomaster CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE repomaster;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 full_name VARCHAR(255),
 email VARCHAR(255) NOT NULL UNIQUE,
 mobile VARCHAR(50),
 password VARCHAR(255) NOT NULL,
 address TEXT,
 role VARCHAR(50),
 reference_admin_email VARCHAR(255),
 status VARCHAR(50),
 failed_attempts INT NOT NULL DEFAULT 0,
 agency_id VARCHAR(100),
 lock_time BIGINT NULL,
 INDEX idx_users_agency_status (agency_id,status),
 INDEX idx_users_agency_role_status (agency_id,role,status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS yard (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 yard_name VARCHAR(255) NOT NULL,
 yard_address TEXT,
 yard_manager_name VARCHAR(255),
 yard_contact_no VARCHAR(50),
 agency_id VARCHAR(100) NOT NULL,
 INDEX idx_yard_agency (agency_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vehicle (
 repo_year VARCHAR(50) NOT NULL,
 repo_month VARCHAR(50) NOT NULL,
 loan_number VARCHAR(255) NOT NULL,
 vehicle_number VARCHAR(100),
 chassis_number VARCHAR(255),
 engine_number VARCHAR(255),
 color VARCHAR(100),
 manufacture_name VARCHAR(255),
 model VARCHAR(255),
 vehicle_make VARCHAR(255),
 vehicle_type VARCHAR(255),
 owner_name VARCHAR(255),
 owner_mobile VARCHAR(50),
 customer_address TEXT,
 customer_area VARCHAR(255),
 agency_id VARCHAR(100),
 agencyid_give_by_finance VARCHAR(255),
 agency_name VARCHAR(255),
 agency_manager VARCHAR(255),
 agency_mobile VARCHAR(50),
 agency_mobile2 VARCHAR(50),
 executive_name VARCHAR(255),
 repo_status VARCHAR(100),
 allocation_dpd VARCHAR(100),
 finance VARCHAR(255),
 branch VARCHAR(255),
 area VARCHAR(255),
 area_manager_name VARCHAR(255),
 area_manager_mobile_no VARCHAR(50),
 area_manager_email_id VARCHAR(255),
 contact_name2 VARCHAR(255),
 contact_name2_designation VARCHAR(255),
 contact_name2_mobile_no VARCHAR(50),
 region_manager_name VARCHAR(255),
 region_manager_mobile_no VARCHAR(50),
 region_manager_email_id VARCHAR(255),
 ref_letter VARCHAR(255),
 total_charges DECIMAL(15,2),
 upload_by VARCHAR(255),
 upload_date DATE,
 yard_id BIGINT NULL,
 PRIMARY KEY (repo_year,repo_month,loan_number),
 INDEX idx_vehicle_number (vehicle_number),
 INDEX idx_vehicle_agency (agency_id),
 INDEX idx_vehicle_status (agency_id,repo_status),
 INDEX idx_vehicle_finance_branch (agency_id,finance,branch),
 INDEX idx_vehicle_yard (yard_id),
 CONSTRAINT fk_vehicle_yard FOREIGN KEY (yard_id) REFERENCES yard(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS search_history (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 vehicle_number VARCHAR(100) NOT NULL,
 user_email VARCHAR(255) NOT NULL,
 user_name VARCHAR(255) NOT NULL,
 search_time DATETIME NOT NULL,
 agency_id VARCHAR(100) NOT NULL,
 INDEX idx_history_agency_time (agency_id,search_time),
 INDEX idx_history_user (user_email),
 INDEX idx_history_vehicle (vehicle_number)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS invoice (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 invoice_number VARCHAR(255) NOT NULL UNIQUE,
 invoice_date DATE,
 repo_year VARCHAR(50),
 repo_month VARCHAR(50),
 invoice_bank VARCHAR(255),
 invoice_address TEXT,
 loan_number VARCHAR(255),
 customer_name VARCHAR(255),
 vehicle_number VARCHAR(100),
 vehicle_type VARCHAR(255),
 vehicle_make VARCHAR(255),
 vehicle_model VARCHAR(255),
 engine_number VARCHAR(255),
 chassis_number VARCHAR(255),
 description_1 TEXT,
 basic1_amount DECIMAL(15,2),
 description_2 TEXT,
 basic2_amount DECIMAL(15,2),
 cgst DECIMAL(15,2),
 sgst DECIMAL(15,2),
 igst DECIMAL(15,2),
 total_basic DECIMAL(15,2),
 gst DECIMAL(15,2),
 invoice_total DECIMAL(15,2),
 remarks TEXT,
 created_by VARCHAR(255),
 created_date DATE,
 gst_percent DECIMAL(7,2),
 payment_date DATE,
 payment_received DECIMAL(15,2),
 payment_status VARCHAR(100),
 agency_id VARCHAR(100),
 INDEX idx_invoice_agency (agency_id),
 INDEX idx_invoice_vehicle (vehicle_number),
 INDEX idx_invoice_loan (loan_number)
) ENGINE=InnoDB;
